// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/v1/proto/todo.proto

package todo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Todo Task State
type TodoState int32

const (
	TodoState_TODO       TodoState = 0
	TodoState_INPROGRESS TodoState = 1
	TodoState_DONE       TodoState = 2
	TodoState_UNDFINED   TodoState = 4
)

// Enum value maps for TodoState.
var (
	TodoState_name = map[int32]string{
		0: "TODO",
		1: "INPROGRESS",
		2: "DONE",
		4: "UNDFINED",
	}
	TodoState_value = map[string]int32{
		"TODO":       0,
		"INPROGRESS": 1,
		"DONE":       2,
		"UNDFINED":   4,
	}
)

func (x TodoState) Enum() *TodoState {
	p := new(TodoState)
	*p = x
	return p
}

func (x TodoState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TodoState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_proto_todo_proto_enumTypes[0].Descriptor()
}

func (TodoState) Type() protoreflect.EnumType {
	return &file_api_v1_proto_todo_proto_enumTypes[0]
}

func (x TodoState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TodoState.Descriptor instead.
func (TodoState) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{0}
}

type ListenRequest_State int32

const (
	ListenRequest_OPEN  ListenRequest_State = 0
	ListenRequest_CLOSE ListenRequest_State = 1
)

// Enum value maps for ListenRequest_State.
var (
	ListenRequest_State_name = map[int32]string{
		0: "OPEN",
		1: "CLOSE",
	}
	ListenRequest_State_value = map[string]int32{
		"OPEN":  0,
		"CLOSE": 1,
	}
)

func (x ListenRequest_State) Enum() *ListenRequest_State {
	p := new(ListenRequest_State)
	*p = x
	return p
}

func (x ListenRequest_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenRequest_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_proto_todo_proto_enumTypes[1].Descriptor()
}

func (ListenRequest_State) Type() protoreflect.EnumType {
	return &file_api_v1_proto_todo_proto_enumTypes[1]
}

func (x ListenRequest_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenRequest_State.Descriptor instead.
func (ListenRequest_State) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{8, 0}
}

type TodoBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taskid        string                 `protobuf:"bytes,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       string                 `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	State         TodoState              `protobuf:"varint,4,opt,name=state,proto3,enum=todo.TodoState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoBody) Reset() {
	*x = TodoBody{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoBody) ProtoMessage() {}

func (x *TodoBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoBody.ProtoReflect.Descriptor instead.
func (*TodoBody) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{0}
}

func (x *TodoBody) GetTaskid() string {
	if x != nil {
		return x.Taskid
	}
	return ""
}

func (x *TodoBody) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TodoBody) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *TodoBody) GetState() TodoState {
	if x != nil {
		return x.State
	}
	return TodoState_TODO
}

// The request message containing the user's ID and request
type TodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	TodoBody      *TodoBody              `protobuf:"bytes,2,opt,name=todoBody,proto3" json:"todoBody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoRequest) Reset() {
	*x = TodoRequest{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoRequest) ProtoMessage() {}

func (x *TodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoRequest.ProtoReflect.Descriptor instead.
func (*TodoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *TodoRequest) GetTodoBody() *TodoBody {
	if x != nil {
		return x.TodoBody
	}
	return nil
}

// The response message containing the Todo Task
type TodoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TodoBody      *TodoBody              `protobuf:"bytes,2,opt,name=todoBody,proto3" json:"todoBody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoReply) Reset() {
	*x = TodoReply{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoReply) ProtoMessage() {}

func (x *TodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoReply.ProtoReflect.Descriptor instead.
func (*TodoReply) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{2}
}

func (x *TodoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TodoReply) GetTodoBody() *TodoBody {
	if x != nil {
		return x.TodoBody
	}
	return nil
}

type TodoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Taskid        string                 `protobuf:"bytes,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoListRequest) Reset() {
	*x = TodoListRequest{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoListRequest) ProtoMessage() {}

func (x *TodoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoListRequest.ProtoReflect.Descriptor instead.
func (*TodoListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{3}
}

func (x *TodoListRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *TodoListRequest) GetTaskid() string {
	if x != nil {
		return x.Taskid
	}
	return ""
}

type TodoListAllReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*TodoBody            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoListAllReply) Reset() {
	*x = TodoListAllReply{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoListAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoListAllReply) ProtoMessage() {}

func (x *TodoListAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoListAllReply.ProtoReflect.Descriptor instead.
func (*TodoListAllReply) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{4}
}

func (x *TodoListAllReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TodoListAllReply) GetItems() []*TodoBody {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{5}
}

func (x *UserRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{6}
}

func (x *UserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenReply) Reset() {
	*x = ListenReply{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenReply) ProtoMessage() {}

func (x *ListenReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenReply.ProtoReflect.Descriptor instead.
func (*ListenReply) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{7}
}

func (x *ListenReply) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	State         ListenRequest_State    `protobuf:"varint,2,opt,name=state,proto3,enum=todo.ListenRequest_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_api_v1_proto_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proto_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proto_todo_proto_rawDescGZIP(), []int{8}
}

func (x *ListenRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *ListenRequest) GetState() ListenRequest_State {
	if x != nil {
		return x.State
	}
	return ListenRequest_OPEN
}

var File_api_v1_proto_todo_proto protoreflect.FileDescriptor

const file_api_v1_proto_todo_proto_rawDesc = "" +
	"\n" +
	"\x17api/v1/proto/todo.proto\x12\x04todo\"\x86\x01\n" +
	"\bTodoBody\x12\x16\n" +
	"\x06taskid\x18\x01 \x01(\tR\x06taskid\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bdue_date\x18\x03 \x01(\tR\adueDate\x12%\n" +
	"\x05state\x18\x04 \x01(\x0e2\x0f.todo.TodoStateR\x05state\"Q\n" +
	"\vTodoRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12*\n" +
	"\btodoBody\x18\x02 \x01(\v2\x0e.todo.TodoBodyR\btodoBody\"Q\n" +
	"\tTodoReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\btodoBody\x18\x02 \x01(\v2\x0e.todo.TodoBodyR\btodoBody\"A\n" +
	"\x0fTodoListRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x16\n" +
	"\x06taskid\x18\x02 \x01(\tR\x06taskid\"R\n" +
	"\x10TodoListAllReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.todo.TodoBodyR\x05items\"%\n" +
	"\vUserRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\"%\n" +
	"\tUserReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vListenReply\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"v\n" +
	"\rListenRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.todo.ListenRequest.StateR\x05state\"\x1c\n" +
	"\x05State\x12\b\n" +
	"\x04OPEN\x10\x00\x12\t\n" +
	"\x05CLOSE\x10\x01*=\n" +
	"\tTodoState\x12\b\n" +
	"\x04TODO\x10\x00\x12\x0e\n" +
	"\n" +
	"INPROGRESS\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\f\n" +
	"\bUNDFINED\x10\x042\xb2\x03\n" +
	"\x04Todo\x12/\n" +
	"\aAddUser\x12\x11.todo.UserRequest\x1a\x0f.todo.UserReply\"\x00\x122\n" +
	"\n" +
	"DeleteUser\x12\x11.todo.UserRequest\x1a\x0f.todo.UserReply\"\x00\x12/\n" +
	"\aAddTodo\x12\x11.todo.TodoRequest\x1a\x0f.todo.TodoReply\"\x00\x122\n" +
	"\n" +
	"UpdateTodo\x12\x11.todo.TodoRequest\x1a\x0f.todo.TodoReply\"\x00\x122\n" +
	"\n" +
	"DeleteTodo\x12\x11.todo.TodoRequest\x1a\x0f.todo.TodoReply\"\x00\x124\n" +
	"\bListTodo\x12\x15.todo.TodoListRequest\x1a\x0f.todo.TodoReply\"\x00\x12;\n" +
	"\fListAllTodos\x12\x11.todo.UserRequest\x1a\x16.todo.TodoListAllReply\"\x00\x129\n" +
	"\vListenTodos\x12\x13.todo.ListenRequest\x1a\x11.todo.ListenReply\"\x000\x01B\x1cZ\x1atodo-app/api/v1/proto;todob\x06proto3"

var (
	file_api_v1_proto_todo_proto_rawDescOnce sync.Once
	file_api_v1_proto_todo_proto_rawDescData []byte
)

func file_api_v1_proto_todo_proto_rawDescGZIP() []byte {
	file_api_v1_proto_todo_proto_rawDescOnce.Do(func() {
		file_api_v1_proto_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_proto_todo_proto_rawDesc), len(file_api_v1_proto_todo_proto_rawDesc)))
	})
	return file_api_v1_proto_todo_proto_rawDescData
}

var file_api_v1_proto_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_proto_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_proto_todo_proto_goTypes = []any{
	(TodoState)(0),           // 0: todo.TodoState
	(ListenRequest_State)(0), // 1: todo.ListenRequest.State
	(*TodoBody)(nil),         // 2: todo.TodoBody
	(*TodoRequest)(nil),      // 3: todo.TodoRequest
	(*TodoReply)(nil),        // 4: todo.TodoReply
	(*TodoListRequest)(nil),  // 5: todo.TodoListRequest
	(*TodoListAllReply)(nil), // 6: todo.TodoListAllReply
	(*UserRequest)(nil),      // 7: todo.UserRequest
	(*UserReply)(nil),        // 8: todo.UserReply
	(*ListenReply)(nil),      // 9: todo.ListenReply
	(*ListenRequest)(nil),    // 10: todo.ListenRequest
}
var file_api_v1_proto_todo_proto_depIdxs = []int32{
	0,  // 0: todo.TodoBody.state:type_name -> todo.TodoState
	2,  // 1: todo.TodoRequest.todoBody:type_name -> todo.TodoBody
	2,  // 2: todo.TodoReply.todoBody:type_name -> todo.TodoBody
	2,  // 3: todo.TodoListAllReply.items:type_name -> todo.TodoBody
	1,  // 4: todo.ListenRequest.state:type_name -> todo.ListenRequest.State
	7,  // 5: todo.Todo.AddUser:input_type -> todo.UserRequest
	7,  // 6: todo.Todo.DeleteUser:input_type -> todo.UserRequest
	3,  // 7: todo.Todo.AddTodo:input_type -> todo.TodoRequest
	3,  // 8: todo.Todo.UpdateTodo:input_type -> todo.TodoRequest
	3,  // 9: todo.Todo.DeleteTodo:input_type -> todo.TodoRequest
	5,  // 10: todo.Todo.ListTodo:input_type -> todo.TodoListRequest
	7,  // 11: todo.Todo.ListAllTodos:input_type -> todo.UserRequest
	10, // 12: todo.Todo.ListenTodos:input_type -> todo.ListenRequest
	8,  // 13: todo.Todo.AddUser:output_type -> todo.UserReply
	8,  // 14: todo.Todo.DeleteUser:output_type -> todo.UserReply
	4,  // 15: todo.Todo.AddTodo:output_type -> todo.TodoReply
	4,  // 16: todo.Todo.UpdateTodo:output_type -> todo.TodoReply
	4,  // 17: todo.Todo.DeleteTodo:output_type -> todo.TodoReply
	4,  // 18: todo.Todo.ListTodo:output_type -> todo.TodoReply
	6,  // 19: todo.Todo.ListAllTodos:output_type -> todo.TodoListAllReply
	9,  // 20: todo.Todo.ListenTodos:output_type -> todo.ListenReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_proto_todo_proto_init() }
func file_api_v1_proto_todo_proto_init() {
	if File_api_v1_proto_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_proto_todo_proto_rawDesc), len(file_api_v1_proto_todo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proto_todo_proto_goTypes,
		DependencyIndexes: file_api_v1_proto_todo_proto_depIdxs,
		EnumInfos:         file_api_v1_proto_todo_proto_enumTypes,
		MessageInfos:      file_api_v1_proto_todo_proto_msgTypes,
	}.Build()
	File_api_v1_proto_todo_proto = out.File
	file_api_v1_proto_todo_proto_goTypes = nil
	file_api_v1_proto_todo_proto_depIdxs = nil
}
